### ISSUE TITLE
Copy climate_match function from trias and its dependencies

### ISSUE THREAD

**Issue by soriadelva** [inbo/ClimateCastR#14]
- [x] Copy climate match function
- [x] Copy all necesarry imports or dependencies (in our case .rda files with Köppen-Geiger climate layers)
- [x] Write an issue in the trias package to notify Damiano about the upcoming move and subsequent deletion of this function

**Comment by soriadelva** [comment]
@SanderDevisscher do I need to change the NAMESPACE file (export(climate_match)) and DESCRIPTION file (add Depends, Imports, and Suggests)?

**Comment by SanderDevisscher** [comment]
You should update our namespace using roxygen2::roxygenise()
